version: '2'

services:
  users-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
      MYSQL_HOST: users-db
  users-app:
    environment:
      MYSQL_HOST: users-db
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - users-db
